# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "develop" branch
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Download mysql docker image
        run: docker pull mysql:8.0.37-debian

      - name: Download sample image which depends kn java 6 image 
        run: docker pull dockerinaction/ch3_myapp

      - name: Show me all the images in my system
        run: docker images

      - name: Show me all images means parent as well
        run: docker images -a

      - name: Start mysql container from mysql image
        run: docker run --name test-mysql -e MYSQL_ROOT_PASSWORD=${{secrets.MYSQL_DB_PASSWORD}} -d mysql:8.0.37-debian

      - name: Docker help command
        run: docker help

      - name: Docker help of command for copy files from container inside location to host location 
        run: docker help cp

      - name: Show me all running container
        run: docker ps

      - name: Stop mysql container
        run: docker stop test-mysql

      - name: Show me all state container mean started stopped etc...
        run: docker ps -a

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
